name: Build

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  push:
    branches:
      - 'feature/**'

jobs: 
  build:
    runs-on: ubuntu-latest
    name: Building
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            3.1.x
            6.0.x

      - name: Cleaning
        run: dotnet clean

      - name: Create DBServer
        run: docker run -e ACCEPT_EULA=Y -e SA_PASSWORD=Bigs3cRet -e MSSQL_PID=Express -p 1433:1433 --name TestDB -d mcr.microsoft.com/mssql/server:2019-latest
      
      - name: Sleep for 30 seconds
        run: sleep 90s
        shell: bash
  
      - name: Create DB
        run: docker exec TestDB /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Bigs3cRet -Q "CREATE DATABASE TestDB;ALTER DATABASE TestDB SET RECOVERY SIMPLE;"
        continue-on-error: true

      - name: Test Generation
        run: dotnet test

      - name: Restore NuGet packages
        run: dotnet restore EAVFramework.sln -p:TargetFramework=net6.0

      - name: Build solution
        run: dotnet build -o ../build/net6.0/ -f net6.0 -c Release --no-restore -m:1

      - name: Restore NuGet packages
        run: dotnet restore EAVFramework.sln -p:TargetFramework=netcoreapp3.1

      - name: Build solution
        run: dotnet build -o ../build/netcoreapp3.1/ -f netcoreapp3.1 -c Release --no-restore -m:1
         
      - name: Archive build to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            build/*
          retention-days: 5