
on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  push:
    branches:
      - 'feature/**'

jobs: 
  build:
    runs-on: ubuntu-latest
    name: Building
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
          with:
          dotnet-version: | 
            3.1.x
            6.0.x

      - name: Cleaning
        run: dotnet clean

      - name: Test Generation
        run: dotnet test

      - name: Restore NuGet packages
        run: dotnet restore EAVFramework.sln -p:TargetFramework=net6.0

      - name: Build solution
        run: dotnet build -o ../build/net6.0/ -f net6.0 -c Release --no-restore -m:1

      - name: Restore NuGet packages
        run: dotnet restore EAVFramework.sln -p:TargetFramework=netcoreapp3.1

      - name: Build solution
        run: dotnet build -o ../build/netcoreapp3.1/ -f netcoreapp3.1 -c Release --no-restore -m:1
         
      - name: Archive build to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            build/*
          retention-days: 5