
on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  push:
    branches:
      - 'feature/**'

jobs:
  test-net60:
    runs-on: ubuntu-latest
    name: Test Net 6.0
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Cleaning
        run: dotnet clean

      - name: Build solution
        run: dotnet test -f net6.0

  test-net31:
    runs-on: ubuntu-latest
    name: Test 3.1
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Cleaning
        run: dotnet clean

      - name: Build solution
        run: dotnet test -f netcoreapp3.1

  build:
    runs-on: ubuntu-latest
    name: Building
    needs: [test-net31, test-net60 ]
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Cleaning
        run: dotnet clean

      - name: Build solution
        run: dotnet test -f net6.0

      - name: Restore NuGet packages
        run: dotnet restore EAVFramework.sln -p:TargetFramework=net6.0

      - name: Build solution
        run: dotnet build -o ../build/net6.0/ -f net6.0 -c Release --no-restore -m:1

      - name: Restore NuGet packages
        run: dotnet restore EAVFramework.sln -p:TargetFramework=netcoreapp3.1

      - name: Build solution
        run: dotnet build -o ../build/netcoreapp3.1/ -f netcoreapp3.1 -c Release --no-restore -m:1
         
      - name: Archive build to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            build/*
          retention-days: 5