name: Release

on:
  push:
    branches:
      - dev
      - main

jobs: 
  test:
    runs-on: ubuntu-latest
    name: Building
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Cleaning
        run: dotnet clean

      - name: Create DBServer
        run: docker run -e ACCEPT_EULA=Y -e SA_PASSWORD=Bigs3cRet -e MSSQL_PID=Express -p 1433:1433 --name TestDB -d mcr.microsoft.com/mssql/server:2019-latest
      
      - name: Sleep for 30 seconds
        run: sleep 90s
        shell: bash
  
      - name: Create DB
        run: docker exec TestDB /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Bigs3cRet -Q "CREATE DATABASE TestDB;ALTER DATABASE TestDB SET RECOVERY SIMPLE;"
        continue-on-error: true

      - name: Test Generation
        run: dotnet test

  release:
    name: Releasing
    needs: test
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Cleaning
        run: dotnet clean 
          
      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Add plugin for conventional commits
        run: npm install conventional-changelog-conventionalcommits
        working-directory: ./.github/workflows

      - name: Add plugin for executing bash commands
        run: npm install @semantic-release/exec -D
        working-directory: ./.github/workflows

      - name: Dry Run Semantic to get next Version nummber
        working-directory: ./.github/workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: pksorensen
          GIT_AUTHOR_EMAIL: poul@kjeldager.com
        run: |
          echo "RELEASE_VERSION=$((npx semantic-release --dry-run).Where({ $_ -like '*Release note*' }) | Out-String | Select-String '[0-9]+\.[0-9]+\.[0-9]+([-][a-zA-z]+[.][0-9]*)?' | % { $_.Matches } | % { $_.Value })" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Print release verison
        run: echo ${env:RELEASE_VERSION}

      - name: Cleaning
        run: dotnet clean

      - name: Restore NuGet packages
        run: dotnet restore EAVFramework.sln

      - name: Package Parser
        run: dotnet pack -c Release -p:PackageVersion=${env:RELEASE_VERSION} -o ./artifacts
        if: ${{ env.RELEASE_VERSION }}

      - name: Release to GitHub and NuGet
        working-directory: .\\.github\\workflows
        env:
          CI_NUGET_API_KEY: ${{ secrets.CI_NUGET_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: pksorensen
          GIT_AUTHOR_EMAIL: poul@kjeldager.com
        run: npx semantic-release